---
title: "SVI 890 MEng 0_0, 2026"
author: "Richard Lubega"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# SVI 890 MEng Test 0_0, 2025

## Initial test

### Log 1: # Exploring DFS output files

```{r, Part-1-a}
# Getting started with the dataset in concrete.csv :
pacman::p_load(ggplot2) 
pacman::p_load(tidymodels)

# Data Preparation
# Load required libraries
pacman::p_load(gridExtra)

# Read the test data (it is a .CSV file)
# Getting started with the dataset in trajectory data :

# Separator
traj.1 <- read.csv(file.choose(),
                   sep = ";",
                   header = TRUE,
                   stringsAsFactors = FALSE,
                   strip.white = TRUE,
                   fill = TRUE)
traj.1 <- traj.1[, names(df) != ""]
head(traj.1)
summary(traj.1)
str(traj.1)

# Tidyverse alternative (recommended for robustness)

pacman::p_load(readr)

gates <- read_delim(file.choose(),
                 delim = ";",
                 trim_ws = TRUE)

summary(gates)
head(gates)
str(gates)

# Explore
# library(dplyr)

traj.1 %>%
  summarise(across(everything(), class)) %>%
  pivot_longer(everything(),
               names_to = "Variable",
               values_to = "Class")


gates %>%
  summarise(across(everything(), class)) %>%
  pivot_longer(everything(),
               names_to = "Variable",
               values_to = "Class")
```


